# Generated by Django 4.1.2 on 2022-10-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CNABFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="",
                        validators=[transactions.models.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                (
                    "nature",
                    models.CharField(
                        choices=[("Saída", "Outcome"), ("Entrada", "Income")],
                        max_length=30,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[("+", "Plus"), ("-", "Minus")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("transaction_time", models.TimeField()),
                ("amount", models.FloatField()),
                ("CPF", models.IntegerField()),
                ("card", models.CharField(max_length=12)),
                ("shop_rep", models.CharField(max_length=14)),
                ("shop_name", models.CharField(max_length=19)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
