# Generated by Django 4.1.2 on 2022-10-17 01:20

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="CPF",
            field=models.CharField(
                max_length=11, validators=[transactions.models.validateCpf]
            ),
        ),
    ]
